apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: images-filters
  labels:
    app.kubernetes.io/name: images-filters
    app.kubernetes.io/component: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: images-filters
