apiVersion: v1
kind: Secret
metadata:
  name: {{ include "images-filters.fullname" . }}-secret
  labels:
    {{- include "images-filters.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- else }}
  redis-password: ""
  {{- end }}
  {{- if .Values.secrets.securityKey }}
  security-key: {{ .Values.secrets.securityKey | b64enc | quote }}
  {{- else }}
  security-key: ""
  {{- end }}
